### ISSUE TITLE
Slurping and barfing changes cursor position

### ISSUE THREAD

**Issue by kindlychung** [guns/vim-sexp#14] opened 2015-04-17 17:00 UTC
For example:

    (f1 (f2 fC3 f4))

cursor position marked by C. After barfing once to the left, the cursor moves to the left paren:

    (f1 f2 (Cf3 f4))

This is quite annoying compared to paredit in emacs. Is there an option to make the cursor stay where it was? 

Thanks!

**Comment by guns** [comment] 2015-04-17 21:17
Hello, thanks for reporting!

This is actually a duplicate of #10, which I am planning on nailing down later today. You could add any further suggestions to that thread.

**Closed by guns** 2015-04-17 21:17 UTC
